account/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
urlpatterns = [
         url(r'^login$',views.user_login,name='user_login'),
         url(r'^logout$',views.user_logout,name='user_logout'),
]

blog/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [
#        url(r'^$',views.home_page,name='home_page'),
        url(r'^blogs$',views.BlogList.as_view(),name='blogs'),
        url(r'^blogs/(?P<id>[0-9]+)$',views.BlogDetail.as_view(),name='blog_detail'),
        ]

restdemo/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
#    url(r'^',include('classtud.urls',namespace='classtud')),
    url(r'^',include('blog.urls',namespace='blog')),
    url(r'^api-auth/', include('rest_framework.urls',namespace='rest_framework')),
    url(r'^account/',include('account.urls',namespace='account',app_name='account')),
]

account/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User,related_name="blogs")
    body = models.TextField()
    published = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-published",)

    def __str__(self):
        return self.title

account/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=255)
    password = forms.CharField(widget=forms.PasswordInput)

account/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .forms import LoginForm
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from django.shortcuts import render
import json

# Create your views here.

#need to be changed
@csrf_exempt
def user_login(request):
    if request.method == "POST":
        received_json_data = json.loads(request.body)
        username = received_json_data["username"]
        password = received_json_data["password"]
        print username
        print password
        user = authenticate(username=username,password=password)
        if user:
            login(request,user)
            return JsonResponse({"login":"0"})
        else:
            return JsonResponse({"login":"1"})

@csrf_exempt
@login_required
def user_logout(request):
    logout(request)
    return JsonResponse({"logout":"0"})

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from .models import Blog
from .serializers import BlogSerializer
from rest_framework import generics
from .permissions import CsrfExemptSessionAuthentication,IsOwnerOrReadOnly
from rest_framework import permissions
from rest_framework.authentication import BasicAuthentication
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

class BlogList(generics.ListCreateAPIView):
    queryset = Blog.objects.all()
    serializer_class = BlogSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,IsOwnerOrReadOnly)
    authentication_classes = (CsrfExemptSessionAuthentication, BasicAuthentication)
    def perform_create(self,serializer):
        serializer.save(author=self.request.user)


class BlogDetail(generics.RetrieveUpdateDestroyAPIView):
    lookup_field = "id"
    queryset = Blog.objects.all()
    serializer_class = BlogSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,IsOwnerOrReadOnly)
    authentication_classes = (CsrfExemptSessionAuthentication, BasicAuthentication)

def home_page(request):
    return render(request,"index.html")

templates/blog-detail/blog-add.template.html
<div class="container">
    <div class="col-md-offset-1">
        <div class="form-inline">
            <label for="title">Title:</label>
            <input type="text" id="title" class="form-control" ng-model="$ctrl.title">
        </div>
    </div>
    <div id="editormd" style="margin-top:20px;">
        <textarea name="content"  style="display:none;" id="body" ng-model="$ctrl.body"></textarea> 
    </div>
    <div class="row col-md-2 col-md-offset-10">
        <button class="btn btn-primary" onclick="addBlog()">提交</button>
    </div>
</div>
<div class="modal fade" id="tip" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">
                模态框（Modal）标题
                </h4>
            </div>
            <div class="modal-body">
                <span id="hint"></span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭
                </button>
                <button type="button" class="btn btn-primary">提交更改
                </button>
            </div>
        </div>
    </div>
</div>
<script src="/templates/node_modules/jquery/dist/jquery.min.js"></script>
<script src="/templates/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
<script type="text/javascript">
$(function() {
    var editor = editormd("editormd", {
        width : "80%",
        height : 500,
        syncScrolling : "single",
        path : "templates/node_modules/editor.md-master/lib/" 
        });
});
var addBlog = function(){
    var title = $("#title").val();
    var body = $("#body").val();
    $.ajax({
       type: "POST",
       url: "blogs",
       data: {"title":title,"body":body},
       success: function(){
            $("#tip").modal();  
            $("#hint").text("add ok");
       },
       error: function(){
            $("#tip").modal();  
            $("#hint").text("add fail");
       }
    })
} 
</script>

templates/blog-detail/blog-delete.template.html
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">
                模态框（Modal）标题
                </h4>
            </div>
            <div class="modal-body">
                {{$ctrl.hint}}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭
                </button>
                <button type="button" class="btn btn-primary">提交更改
                </button>
            </div>
        </div>
    </div>
</div>
<script src="/templates/node_modules/jquery/dist/jquery.min.js"></script>
<script src="/templates/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
<script type="text/javascript">
$(function() {
    $('#myModal').modal({
        keyboard: true
})
});
</script>

templates/blog-detail/blog-detail.template.html
<!--
<link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}"/>
-->
<div id="editormd-view">
    <textarea id="append-test" style="display:none;">
{{$ctrl.blog.body}}
    </textarea>
</div>

<link rel="stylesheet" href="/templates/node_modules/editor.md-master/examples/css/style.css" />
<link rel="stylesheet" href="/templates/node_modules/editor.md-master/css/editormd.preview.css" />
<script src="/templates/node_modules/jquery/dist/jquery.min.js"></script> 
<script src="/templates/node_modules/editor.md-master/lib/marked.min.js"></script>
<script src="/templates/node_modules/editor.md-master/lib/prettify.min.js"></script>
<script src="/templates/node_modules/editor.md-master/lib/raphael.min.js"></script>
<script src="/templates/node_modules/editor.md-master/lib/underscore.min.js"></script>
<script src="/templates/node_modules/editor.md-master/lib/sequence-diagram.min.js"></script>
<script src="/templates/node_modules/editor.md-master/lib/flowchart.min.js"></script>
<script src="/templates/node_modules/editor.md-master/lib/jquery.flowchart.min.js"></script>
<script src="/templates/node_modules/editor.md-master/editormd.js"></script>
<script type="text/javascript">
$(function(){
    editormd.markdownToHTML("editormd-view",{
        htmlDecode:"style,script,iframe" ,
        emoji:true,
        taskList:true,
        tex:true,
        flowChart:true,
        sequenceDiagram:true,
    });
});
</script>

templates/blog-detail/blog-edit.template.html
<div class="container">
    <div class="col-md-offset-1">
        <div class="form-inline">
            <label for="title">Title:</label>
            <input type="text" id="title" class="form-control" ng-model="$ctrl.blog.title">
        </div>
    </div>

    <div id="editormd" style="margin-top:20px;"><!--{{ article_post_form.body }}-->
    <textarea style="display:none;" id="id_body">
{{$ctrl.blog.body}}
    </textarea>
    </div>
    <div class="row col-md-2 col-md-offset-10">
<button type="button" class="btn btn-primary" onclick="editBlog()">提交</button>
    </div>
</div>

<script type="text/javascript">
$(function(){
    var editor = editormd("editormd",{
        width:"80%" ,
        height:500,
        path:"templates/node_modules/editor.md-master/lib/",
    });
}); 
var editBlog = function(){
    var title = $("#title").val();
    var body = $("#id_body").val();
    var urlstr = location.href;
    var strs = new Array();
    strs = urlstr.split("/");
    blogId = strs.pop();
    $.ajax({
        url: "/blogs/"+blogId,
        type: "PUT",
        data: {"title":title,"body":body},
        success: function(){
            $("#tip").modal();  
            console.log("edit success")
            $("#hint").text("edit success");
        },
        error: function(){
            $("#tip").modal();  
            console.log("edit error")
            $("#hint").text("edit error");
        }
    });
}
</script>

<div class="modal fade" id="tip" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">
                模态框（Modal）标题
                </h4>
            </div>
            <div class="modal-body">
                <span id="hint"></span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭
                </button>
                <button type="button" class="btn btn-primary">提交更改
                </button>
            </div>
        </div>
    </div>
</div>

templates/blog-detail/blog-mgm.template.html
<div class="container">
    <div class="row col-md-offset-2 col-md-8">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>名称</th> 
                    <th>作者</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                <tr ng-repeat="blog in $ctrl.blogs">
                    <td>{{blog.title}}</td> 
                    <td>{{blog.author}}</td>
                    <td><a ui-sref="blogedit({blogId:blog.id})"><span class="glyphicon glyphicon-pencil"></span></a>／<a ui-sref="blogmgm.blogdelete({blogId:blog.id})"><span class="glyphicon glyphicon-trash"></span ></a></td>
                </tr>
            </tbody>
        </table>
        <button class="btn btn-default"><a ui-sref="blogadd">增加</a></button>

        <ui-view></ui-view>
    </div>
</div>

templates/blog-list/blog-list.template.html
<div class="container">
    <h3 style="display: inline;">SalorMoon </h3><span style="margin-left:10px;color:#999;">意识和耐心</span>
        <hr>
    <ul class="col-md-8">
        <li ng-repeat="blog in $ctrl.blogs" style="list-style:none;">
            <h3><a ui-sref="blogdetail({blogId:blog.id})" class="goon">{{blog.title}}</a></h4>
            <span style="color:#999;">By&nbsp;{{blog.author}}</span>&nbsp;<span style="color:#999;">{{blog.published|date:'yyyy-MM-dd'}}</span>
            <p>{{blog.body|limitTo:70}}...</p>
            <p><a ui-sref="blogdetail({blogId:blog.id})">继续阅读...</span></a></p>
            <hr>
        </li>
    </ul>
</div>
<style>
.goon {
    color: #333;
}
.goon:hover {
    text-decoration: none;
    color: #EB5B4C;
}
</style>

templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html ng-app="blogApp">
    <head>
        <meta charset="utf-8">
        <title>博客系统</title>
        <link rel="stylesheet" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}" />
        <link rel="stylesheet" href="{% static 'node_modules/editor.md-master/css/editormd.css'%}" />
        <link rel="stylesheet" href="{% static 'node_modules/editor.md-master/css/editormd.preview.css'%}" />
        <script type="text/javascript" src="{% static 'node_modules/jquery/dist/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'node_modules/editor.md-master/editormd.js'%}"></script>
        <script type="text/javascript" src="{% static 'node_modules/bootstrap/dist/js/bootstrap.min.js'%}"></script>
        <script type="text/javascript" src="{% static 'node_modules/angular/angular.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'node_modules/angular-resource/angular-resource.min.js'%}"></script>
        <script type="text/javascript" src="{% static 'node_modules/angular-ui-router/angular-ui-router.js'%}"></script>
        <script type="text/javascript" src="{% static 'app.module.js'%}"></script>
        <script type="text/javascript" src="{% static 'app.config.js'%}"></script>
        <script type="text/javascript" src="{% static 'core/core.module.js'%}"></script>
        <script type="text/javascript" src="{% static 'core/blog/blog.module.js'%}"></script>
        <script type="text/javascript" src="{% static 'core/blog/blog.service.js' %}"></script>
        <script type="text/javascript" src="{% static 'blog-list/blog-list.module.js' %}"></script>
        <script type="text/javascript" src="{% static 'blog-list/blog-list.component.js' %}"></script>
        <script type="text/javascript" src="{% static 'blog-detail/blog-detail.module.js'%}"></script>
        <script type="text/javascript" src="{% static 'blog-detail/blog-detail.component.js'%}"></script>
        <script type="text/javascript" src="{% static 'newaccount/account.module.js'%}"></script>
        <script type="text/javascript" src="{% static 'newaccount/account.component.js'%}"></script>
        <script type="text/javascript" src="{% static 'navigate/navigate.module.js'%}"></script>
        <script type="text/javascript" src="{% static 'navigate/navigate.component.js'%}"></script>
    </head>
    <body>
        <!--        <a ui-sref="bloglist">bloglist</a> -->
        <navigate></navigate>
        <ui-view></ui-view> 
    </body>
</html>

templates/navigate/navigate.template.html
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fulid">
        <div class="navbar-header">
            <a class="navbar-brand" ui-sref="bloglist">SalorMoon</a>
        </div>
        <div>
            <ul class="nav navbar-nav">
                <li><a ui-sref="bloglist">Home</a></li>
                <li ng-show="$ctrl.login"><a ui-sref="blogmgm">管理</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li ng-hide="$ctrl.login"><a ui-sref="login"><span class="glyphicon glyphicon-log-in" ></span> 登录</a></li>
                <li ng-show="$ctrl.login"><a href="#" ng-click="$ctrl.logout()"><span class="glyphicon glyphicon-log-out"></span>注销</a></li>
            </ul>
        </div>
        <div class="nav navbar-nav navbar-right">
            <p class="navbar-text">{{$ctrl.user}}</p>
        </div>
    </div>
</nav>

templates/newaccount/account.template.html
<div class="container" style="margin-top:100px;">
<div class="row text-center">
    <div class="col-md-offset-4 col-md-4">
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">@</span>
            <input class="form-control" type="text" id="username" placeholder="用户名" ng-model="$ctrl.username">
        </div>
        <br>
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">@</span>
            <input class="form-control" type="password" id="password" placeholder="密码" ng-model="$ctrl.password">
        </div>
        <br>
        <button class="btn btn-default" style="width:300px;" ng-click="$ctrl.login($ctrl.username,$ctrl.password)">登录</button>
    </div>
    </div>
</div>
</div>